export const DEFAULT_ACTION = 'app/Moderator/DEFAULT_ACTION';
export const FETCH_CONTENT_ACTION = 'app/Moderrator/FETCH_CONTENT_ACTION';
export const FETCH_CONTENT_SUCCESS_ACTION =
  'app/Moderrator/FETCH_CONTENT_SUCCESS_ACTION';
export const FETCH_CONTENT_FAILER_ACTION =
  'app/Moderrator/FETCH_CONTENT_FAILER_ACTION';

export const PUT_CONTENT_ACCEPT_STATUS_FAILER_ACTION =
  'app/Moderrator/PUT_CONTENT_ACCEPT_STATUS_FAILER_ACTION';
export const PUT_CONTENT_ACCEPT_STATUS_SUCCESS_ACTION =
  'app/Moderrator/PUT_CONTENT_ACCEPT_STATUS_SUCCESS_ACTION';
export const PUT_CONTENT_ACCEPT_STATUS_ACTION =
  'app/Moderrator/PUT_CONTENT_ACCEPT_STATUS_ACTION';

export const PUT_CONTENT_REJECT_STATUS_FAILER_ACTION =
  'app/Moderrator/PUT_CONTENT_REJECT_STATUS_FAILER_ACTION';
export const PUT_CONTENT_REJECT_STATUS_SUCCESS_ACTION =
  'app/Moderrator/PUT_CONTENT_REJECT_STATUS_SUCCESS_ACTION';
export const PUT_CONTENT_REJECT_STATUS_ACTION =
  'app/Moderrator/PUT_CONTENT_REJECT_STATUS_ACTION';

export const LOAD_MORE_ACTION = 'app/Moderrator/LOAD_MORE_ACTION';
export const LOAD_MORE_SUCCESS = 'app/Moderrator/LOAD_MORE_SUCCESS';

export const FILTER_ACTION_MOD = 'app/Moderrator/FILTER_ACTION_MOD';
export const SUCCESS_FILTER_ACTION = 'app/Moderrator/SUCCESS_FILTER_ACTION';

export const FILTER_CHANGE_ACTION = 'app/Moderrator/FILTER_CHANGE_ACTION';
